apiVersion: 1
datasources:
  - name: PostgreSQL
    type: grafana-postgresql-datasource
    uid: df9o2whw2o7wgb
    access: proxy
    url: pgbouncer:5432
    database: umh
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    isDefault: true
